name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: pddg/latex:1.2.0
      volumes:
        - $GITHUB_WORKSPACE:/workdir
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: bash bin/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: ./main.pdf
